paths:
  input_table: "input.xlsx"
  refs:
    # Path to the reference folder for container mounting
    path: "/media/data/NGS/refs"
    # Absolute paths to reference files
    ## Genomes
    genome_human: "/media/data/NGS/refs/broad/Homo_sapiens_assembly38.fasta"
    genome_host: "/media/data/NGS/refs/mm39/mm39.fa"
    ## Exome regions
    regions_bedfile: "/media/data/NGS/refs/SureSelectHumanAllExon/V8UTR/S33613271_Regions.bed"
    ## BQSR
    known_sites:
      - "/media/data/NGS/refs/broad/Homo_sapiens_assembly38.dbsnp138.vcf"
      - "/media/data/NGS/refs/broad/Homo_sapiens_assembly38.known_indels.vcf.gz"
      - "/media/data/NGS/refs/broad/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    ## Mutect2 
    germline_resource: "/media/data/NGS/refs/gatk-BP-somatic-hg38/af-only-gnomad.hg38.vcf.gz"
    ## Funcotator
    funcotator_data_sources: "/media/data/NGS/refs/funcotator/funcotator_dataSources.v1.8.hg38.20230908s"

resources:
  threads: 64
  java_max_gb: 480
  java_min_gb: 80
  strelka_max_gb: 480

tools:
  gatk:
    image: "broadinstitute/gatk"
    version: "4.6.1.0"
  strelka:
    image: "mcfonsecalab/strelka"
    version: "2.9.10"
  somaticseq:
    image: "lethalfang/somaticseq"
    version: "latest"

params:
    library_prep: "SureSelectV8UTR"
    genome_version: "hg38" # need to be specified for Funcotator
    xengsort:
      index_size: 4500000000
      index_fill: 0.88
      index_k: 25
      chunksize: 16.0
      prefetch: 1
    varscan:
      min_coverage: 5 # Minimum coverage in normal and tumor to call variant
      min_var_freq: 0.05 # Minimum variant frequency to call a heterozygote
      p_value: 0.99 # P-value threshold to call a heterozygote
      somatic_p_value: 0.01 # P-value threshold to call a somatic site
      filter_min_coverage: 5
      filter_p_value: 0.01 # Default p-value threshold for calling variants [1e-01]
      filter_min_reads: 2 # Minimum supporting reads for a variant [2]
      filter_min_strands: 1 # Minimum # of strands on which variant observed (1 or 2) [1]
      filter_min_avg_qual: 20 # Minimum average base quality for variant-supporting reads [20]
      filter_min_var_freq: 0.05 # Minimum variant allele frequency threshold [0.20]
    somaticseq:
      pass_threshold: 0.5 # SCORE for PASS (default: 0.5)
      lowqual_threshold: 0.1 # SCORE for LowQual (default: 0.1)
      homozygous_threshold: 0.85 # VAF for homozygous (default: 0.85)
      heterozygous_threshold: 0.01 # VAF for heterozygous (default: 0.01)
      minimum_mapping_quality: 1 # Minimum mapping quality below which is considered poor (default: 1)
      minimum_base_quality: 5 # Minimum base quality below which is considered poor (default: 5)
      minimum_num_callers: 1 # Minimum number of tools to be considered (default: 0.5)