paths:
  refs:
    genome_human: "/media/data/NGS/refs/broad/Homo_sapiens_assembly38.fasta"

resources:
  bwa_threads: 16
  java_max_gb: 480
  java_min_gb: 80

tools:
  gatk_version: "4.6.1.0"  # Or your preferred version

params:
    library_prep: "SureSelectV8UTR"
