samplesheet: "P005_full.csv"

probe_configs:
  "V6+UTR":
    library_prep: "SureSelectV6UTR"
    regions_bedfile: "/mnt/data/NGS/refs/SureSelectHumanAllExon/V6UTR/S07604624_Regions.bed"
    cnvkit_targets:     "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V6/targets.bed"
    cnvkit_antitargets: "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V6/antitargets.bed"
    cnvkit_ref_m:       "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V6/reference_male.cnn"
    cnvkit_ref_f:       "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V6/reference_female.cnn"
  "V8+UTR":
    library_prep: "SureSelectV8UTR"
    regions_bedfile: "/mnt/data/NGS/refs/SureSelectHumanAllExon/V8UTR/S33613271_Regions.bed"
    cnvkit_targets:     "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V8/targets.bed"
    cnvkit_antitargets: "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V8/antitargets.bed"
    cnvkit_ref_m: "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V8/reference_male.cnn"
    cnvkit_ref_f: "/mnt/data/NGS/refs/CNVkit/CNVkit-nf/reference_V8/reference_female.cnn"

refs:
  # Absolute paths to reference directory:
  path: "/mnt/data/NGS/refs"
  # Absolute paths to reference files:
  ## Genomes
  genome_human: "/mnt/data/NGS/refs/broad/Homo_sapiens_assembly38.fasta"
  genome_host: "/mnt/data/NGS/refs/mm39/mm39.fa"
  ## BQSR
  known_sites:
    - "/mnt/data/NGS/refs/broad/Homo_sapiens_assembly38.dbsnp138.vcf"
    - "/mnt/data/NGS/refs/broad/Homo_sapiens_assembly38.known_indels.vcf.gz"
    - "/mnt/data/NGS/refs/broad/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  ## Mutect2 
  germline_resource: "/mnt/data/NGS/refs/gatk-BP-somatic-hg38/af-only-gnomad.hg38.vcf.gz"
  ## Funcotator
  funcotator_data_sources: 
    genome_version: "hg38"
    path: "/mnt/data/NGS/refs/funcotator/funcotator_dataSources.v1.8.hg38.20230908s"
  ## Predownloaded AnnotSV cache
  annotsv_annotations:
    genome_build: "GRCh38"
    path: "/mnt/data/NGS/refs/annotsv/AnnotSV_annotations"
  purecn:
    genome: "hg38"

params:
    xengsort:
      index_size: 4500000000
      index_fill: 0.88
      index_k: 25
      chunksize: 16.0
      prefetch: 1
    cnvkit:
      filter_ci: true  # Set to true to enable segments filtering based on CI

resources:
  threads: 32
  java_max_gb: 256
  java_min_gb: 32
  manta_max_gb: 256